name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Gr4vy UIKit Sample App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Build
        run: |
          # Get available simulators
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          echo "Using device: $device"
          
          # Build the project with the correct scheme
          xcodebuild build \
            -project gr4vy-uikit.xcodeproj \
            -scheme "Gr4vy UIKit Sample App" \
            -destination "platform=iOS Simulator,name=$device" \
            -configuration Debug
